spring.application.name=emotionhubproject


#encoding set UTF-8
spring.servlet.encoding.charset=UTF-8
spring.servlet.encoding.force=true

# Mustache ???? ?? ??? ???? ??, ??? ???? ?? ?? ? ?? ????? ??
spring.mustache.prefix=file:src/main/resources/templates/
spring.mustache.suffix=.mustache
spring.mustache.cache=false

#H2 database connect configuration
spring.datasource.url=jdbc:h2:mem:testdb;
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update

# H2 db console open
spring.h2.console.enabled=true

# SQL display
spring.jpa.show-sql=true

#Hibernate sql display
spring.jpa.properties.hibernate.format_sql=true
